version: "3.4"

services:
  nginx:
    image: kompadre/nginx-with-purge
    ports:
      - "80:80"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/conf.d:/etc/nginx/conf.d"
      - "./config/fastcgi_params:/etc/nginx/fastcgi_params"
      - ./html:/var/www/html
    links:
      - php      
  php:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html
      - ./html/index.php:/index.php
